# Step 2 playground: mock-sap
SAP owns the weekly clearance list + business rules. This notebook walks the whole loop by hand:

```
generate → SAP Postgres        (SAP is seeded with candidates + rules)
SAP  --GET candidates-->  sap_ingest  → DuckDB
DuckDB → stub_sender  --POST prices-->  SAP  (per-record results)
SAP  --GET conditions--> check what SAP holds
```

**Before running:** in a terminal at the project root run `docker compose up -d --build`, then pick the `pricing` kernel.

In [1]:
import os, sys
ROOT = os.path.abspath("..") if os.path.basename(os.getcwd()) == "playground" else os.getcwd()
os.chdir(ROOT); sys.path.insert(0, ROOT)
os.environ.setdefault("SAP_BASE_URL", "http://localhost:8001")
os.environ.setdefault("SAP_READ_KEY", "dev-read-key")
os.environ.setdefault("SAP_WRITE_KEY", "dev-write-key")
os.environ.setdefault("DATABASE_URL", "postgresql://pricing:pricing@localhost:5432/pricing")
import httpx, duckdb, pandas as pd
from collections import Counter
pd.set_option("display.width", 170); pd.set_option("display.max_columns", 30)
WEEK, DB = "2026-W39", "data/warehouse.duckdb"
SAP = os.environ["SAP_BASE_URL"]
read  = httpx.Client(base_url=SAP, headers={"X-API-Key": os.environ["SAP_READ_KEY"]},  timeout=30)
write = httpx.Client(base_url=SAP, headers={"X-API-Key": os.environ["SAP_WRITE_KEY"]}, timeout=30)
print("project root:", ROOT)

project root: /Users/xuhui/Documents/VScode/AI_pricing_system

## 1. Is mock-sap up?

In [2]:
print(httpx.get(f"{SAP}/healthz").json())

{'status': 'ok'}

## 2. Seed both stores (fresh start)
Rebuilds DuckDB (history only) **and** re-seeds SAP's Postgres (candidates + rules, and clears any received prices).
Close other DuckDB connections first (e.g. the step 1 notebook), or the file is locked.

In [3]:
from jobs.data_gen.generate import write as write_duckdb, build, SAP_TABLES
from jobs.data_gen.seed_sap import seed_sap
print("DuckDB :", write_duckdb(DB, seed=42))
print("SAP PG :", seed_sap({k: v for k, v in build(42).items() if k in SAP_TABLES}))

DuckDB : {'weeks': 13, 'products': 128, 'stores': 13, 'sales': 139776, 'price_history': 4608, 'inventory': 621, 'seed_manifest': 5}
SAP PG : {'clearance_candidates': 624, 'business_rules': 205}

## 3. Keys are enforced
No key → 401. Read key on POST → 403 (the read key can never write prices).

In [4]:
print("no key, GET      :", httpx.get(f"{SAP}/clearance/candidates", params={"week": WEEK}).status_code)
print("read key, POST   :", read.post("/pricing/markdown-prices", json={"run_id": "x", "week": WEEK, "prices": []}).status_code)
print("write key, POST  :", write.post("/pricing/markdown-prices", json={"run_id": "x", "week": WEEK, "prices": []}).status_code)

no key, GET      : 401
read key, POST   : 403
write key, POST  : 200

## 4. What SAP sends: this week's candidate list with business rules

In [5]:
r = read.get("/clearance/candidates", params={"week": WEEK}).json()
cands = pd.DataFrame(r["items"])
print("rows:", r["count"])
cands.head(10)

rows: 138

       week     sku  pack_type  pack_qty region  shelf_price  week_no  current_price  price_floor  max_markdown_pct  max_clearance_weeks    rule_version
0  2026-W39  100000     Single         1    NSW        67.99        4          46.00          NaN               NaN                  NaN             NaN
1  2026-W39  100000     Single         1    QLD        67.99        4          52.66          NaN               NaN                  NaN             NaN
2  2026-W39  100000     Single         1    VIC        67.99        4          46.82          NaN               NaN                  NaN             NaN
3  2026-W39  100002  Multipack         6    NSW       221.94        1         221.94       130.04               0.5                 20.0  SAP-R-2026-W39
4  2026-W39  100002  Multipack         6    QLD       221.94        1         221.94       130.04               0.5                 20.0  SAP-R-2026-W39
5  2026-W39  100002  Multipack         6    VIC       221.94        1         221.94       130.04               0.5                 20.0  SAP-R-2026-W39
6  2026-W39  100004  Multipack         6    NSW       365.94        5         270.30       169.03               0.5                 20.0  SAP-R-2026-W39
7  2026-W39  100004  Multipack         6    QLD       365.94        5         242.24       169.03               0.5                 20.0  SAP-R-2026-W39
8  2026-W39  100004  Multipack         6    VIC       365.94        5         269.50       169.03               0.5                 20.0  SAP-R-2026-W39
9  2026-W39  100006     Single         1    NSW        45.99        6          30.35          NaN               NaN                  NaN             NaN

In [6]:
# rows SAP sent WITHOUT a rule (missing rule) and the article that has no product master
cands[cands.price_floor.isna()]

         week     sku pack_type  pack_qty region  shelf_price  week_no  current_price  price_floor  max_markdown_pct  max_clearance_weeks rule_version
0    2026-W39  100000    Single         1    NSW        67.99        4          46.00          NaN               NaN                  NaN          NaN
1    2026-W39  100000    Single         1    QLD        67.99        4          52.66          NaN               NaN                  NaN          NaN
2    2026-W39  100000    Single         1    VIC        67.99        4          46.82          NaN               NaN                  NaN          NaN
9    2026-W39  100006    Single         1    NSW        45.99        6          30.35          NaN               NaN                  NaN          NaN
10   2026-W39  100006    Single         1    QLD        45.99        6          28.29          NaN               NaN                  NaN          NaN
11   2026-W39  100006    Single         1    VIC        45.99        6          24.72          NaN               NaN                  NaN          NaN
135  2026-W39  999999    Single         1    NSW        24.99        1          19.99          NaN               NaN                  NaN          NaN
136  2026-W39  999999    Single         1    QLD        24.99        1          19.99          NaN               NaN                  NaN          NaN
137  2026-W39  999999    Single         1    VIC        24.99        1          19.99          NaN               NaN                  NaN          NaN

## 5. Ingest: SAP → DuckDB
The stand-in for the weekly Airflow ingestion. Writes `clearance_candidates` and `business_rules` for the week into DuckDB.

In [7]:
from jobs.sap_ingest import ingest
print(ingest(read, WEEK, DB))
con = duckdb.connect(DB, read_only=True)
display(con.sql("SELECT week, count(*) AS candidate_rows FROM clearance_candidates GROUP BY 1").df())
display(con.sql("SELECT week, count(*) AS rules FROM business_rules GROUP BY 1").df())
con.close()

{'candidates': 138, 'rules': 43, 'candidates_without_rule': 9}

       week  candidate_rows
0  2026-W39             138

       week  rules
0  2026-W39     43

## 6. Stub sender: DuckDB → SAP
Prices each row at `current_price × 0.9`, clamped to the floor / max markdown, never above last week's price, multipack per-item ≥ Single. Rows it cannot price are skipped and reported.

In [8]:
from jobs.stub_sender import build_prices, send
prices, skipped = build_prices(WEEK, discount=0.10)
print(f"{len(prices)} prices built, {len(skipped)} skipped")
display(pd.DataFrame(skipped).groupby("reason").size().rename("rows"))
pd.DataFrame(prices).head(8)

126 prices built, 9 skipped

reason
FLOOR_ABOVE_PRICE    3
MISSING_RULE         6
Name: rows, dtype: int64

      sku  pack_qty region  markdown_price  valid_from    valid_to
0  100008         1    NSW            7.28  2026-09-21  2026-09-27
1  100008         1    QLD            7.42  2026-09-21  2026-09-27
2  100008         1    VIC            7.56  2026-09-21  2026-09-27
3  100011         1    NSW           21.24  2026-09-21  2026-09-27
4  100011         1    QLD           21.24  2026-09-21  2026-09-27
5  100011         1    VIC           21.24  2026-09-21  2026-09-27
6  100014         1    NSW           13.56  2026-09-21  2026-09-27
7  100014         1    QLD           12.68  2026-09-21  2026-09-27

In [9]:
RUN = "2026-W39-manual-1"
results = send(write, WEEK, RUN, prices, batch_size=50)
print(Counter((r["status"], r["code"]) for r in results))
pd.DataFrame(results).head(8)

Counter({('ACCEPTED', 'OK'): 126})

      sku  pack_qty region    status code   message  duplicate
0  100008         1    NSW  ACCEPTED   OK  accepted      False
1  100008         1    QLD  ACCEPTED   OK  accepted      False
2  100008         1    VIC  ACCEPTED   OK  accepted      False
3  100011         1    NSW  ACCEPTED   OK  accepted      False
4  100011         1    QLD  ACCEPTED   OK  accepted      False
5  100011         1    VIC  ACCEPTED   OK  accepted      False
6  100014         1    NSW  ACCEPTED   OK  accepted      False
7  100014         1    QLD  ACCEPTED   OK  accepted      False

## 7. Idempotency: send the same run again
Same `run_id + sku + pack_qty + region + valid_from` → returns the stored result, nothing is duplicated.

In [10]:
again = send(write, WEEK, RUN, prices, batch_size=50)
print(Counter((r["status"], r["code"], r["duplicate"]) for r in again))

Counter({('ACCEPTED', 'OK', True): 126})

## 8. A new run for the same validity period → rejected (overlap)
SAP already holds conditions for those SKUs and dates.

In [11]:
overlap = send(write, WEEK, "2026-W39-manual-2", prices[:5], batch_size=50)
pd.DataFrame(overlap)[["sku", "pack_qty", "region", "status", "code", "message"]]

      sku  pack_qty region    status              code                                            message
0  100008         1    NSW  REJECTED  VALIDITY_OVERLAP  validity overlaps existing condition record (r...
1  100008         1    QLD  REJECTED  VALIDITY_OVERLAP  validity overlaps existing condition record (r...
2  100008         1    VIC  REJECTED  VALIDITY_OVERLAP  validity overlaps existing condition record (r...
3  100011         1    NSW  REJECTED  VALIDITY_OVERLAP  validity overlaps existing condition record (r...
4  100011         1    QLD  REJECTED  VALIDITY_OVERLAP  validity overlaps existing condition record (r...

## 9. Partial failure: a batch with bad records
One good record per its own rules, others rejected individually. The batch is never all-pass / all-fail.

In [12]:
some = cands[cands.price_floor.notna()].iloc[-1]
batch = [
    {"sku": some.sku, "pack_qty": int(some.pack_qty), "region": some.region,
     "markdown_price": round(some.current_price * 0.8, 2), "valid_from": "2026-09-28", "valid_to": "2026-10-04"},  # ok (later dates, no overlap)
    {"sku": some.sku, "pack_qty": int(some.pack_qty), "region": some.region, "markdown_price": -5,
     "valid_from": "2026-09-21", "valid_to": "2026-09-27"},                       # negative price
    {"sku": "000000", "pack_qty": 1, "region": "VIC", "markdown_price": 9.99,
     "valid_from": "2026-09-21", "valid_to": "2026-09-27"},                       # not on SAP's list
    {"sku": some.sku},                                                            # missing fields
]
r = write.post("/pricing/markdown-prices", json={"run_id": "2026-W39-manual-3", "week": WEEK, "prices": batch}).json()
print(r["summary"])
pd.DataFrame(r["results"])

{'received': 4, 'accepted': 1, 'rejected': 3, 'duplicates': 0}

      sku  pack_qty region    status         code                                            message  duplicate
0  100099       1.0    VIC  ACCEPTED           OK                                           accepted      False
1  100099       1.0    VIC  REJECTED   BAD_FORMAT  markdown_price must be positive with at most 2...      False
2  000000       1.0    VIC  REJECTED  NOT_ON_LIST                 not on the 2026-W39 clearance list      False
3  100099       NaN    NaN  REJECTED   BAD_FORMAT                             missing field pack_qty      False

## 10. What SAP now holds (GET conditions) vs what we sent

In [13]:
held = pd.DataFrame(read.get("/pricing/conditions", params={"week": WEEK}).json()["items"])
sent = pd.DataFrame(prices).rename(columns={"markdown_price": "sent_price"})
cmp = sent.merge(held, on=["sku", "pack_qty", "region"], how="left")
print("sent:", len(sent), "| held by SAP for W39:", len(held), "| sent but not held:", cmp.price.isna().sum(),
      "| price differs:", (cmp.price.notna() & (cmp.price != cmp.sent_price)).sum())
held.head()

sent: 126 | held by SAP for W39: 127 | sent but not held: 0 | price differs: 1

              run_id      week     sku  pack_qty region   price  valid_from    valid_to
0  2026-W39-manual-1  2026-W39  100002         6    NSW  221.94  2026-09-21  2026-09-27
1  2026-W39-manual-1  2026-W39  100002         6    QLD  221.94  2026-09-21  2026-09-27
2  2026-W39-manual-1  2026-W39  100002         6    VIC  221.94  2026-09-21  2026-09-27
3  2026-W39-manual-1  2026-W39  100004         6    NSW  270.30  2026-09-21  2026-09-27
4  2026-W39-manual-1  2026-W39  100004         6    QLD  242.24  2026-09-21  2026-09-27

## 11. Reset SAP's received prices (to rerun sections 6-10)
Truncates only `price_conditions`; the candidate list and rules stay.

In [15]:
from shared import db
from shared.sap_schema import schema
with db.connect() as c:
    c.execute(f"TRUNCATE {schema()}.price_conditions")
print("cleared; SAP holds", read.get("/pricing/conditions", params={"week": WEEK}).json()["count"], "conditions")

cleared; SAP holds 0 conditions