# Step 3 playground: pricing engine
Simple engine: **week 1 no discount, then +5 points of shelf price per week**, within hard rules (SAP floor, never below 50% off shelf, multipack per-item price ≥ its Single, never above last week's price, at most `max_clearance_weeks` = 10 weeks).

```
SAP → sap_ingest → DuckDB → pricing engine → price_recommendations → SAP (per-record result)
```
**Before running:** `docker compose up -d` at the project root, then pick the `pricing` kernel.

In [1]:
import os, sys
ROOT = os.path.abspath("..") if os.path.basename(os.getcwd()) == "playground" else os.getcwd()
os.chdir(ROOT); sys.path.insert(0, ROOT)
os.environ.setdefault("SAP_BASE_URL", "http://localhost:8001")
os.environ.setdefault("SAP_READ_KEY", "dev-read-key")
os.environ.setdefault("SAP_WRITE_KEY", "dev-write-key")
os.environ.setdefault("DATABASE_URL", "postgresql://pricing:pricing@localhost:5432/pricing")
import httpx, duckdb, pandas as pd
from collections import Counter
pd.set_option("display.width", 170); pd.set_option("display.max_columns", 30)
WEEK, DB, RUN = "2026-W39", "data/warehouse.duckdb", "2026-W39-notebook"
SAP = os.environ["SAP_BASE_URL"]
read  = httpx.Client(base_url=SAP, headers={"X-API-Key": os.environ["SAP_READ_KEY"]},  timeout=30)
write = httpx.Client(base_url=SAP, headers={"X-API-Key": os.environ["SAP_WRITE_KEY"]}, timeout=30)
print("mock-sap:", httpx.get(f"{SAP}/healthz").json())

mock-sap: {'status': 'ok'}

## 1. Fresh start: seed DuckDB history + SAP, then ingest this week's list from SAP
Close other DuckDB connections first (e.g. the step 1 notebook), or the file is locked.

In [2]:
from jobs.data_gen.generate import write as write_duckdb, build, SAP_TABLES
from jobs.data_gen.seed_sap import seed_sap
from jobs.sap_ingest import ingest
write_duckdb(DB, seed=42)
seed_sap({k: v for k, v in build(42).items() if k in SAP_TABLES})
print(ingest(read, WEEK, DB))

{'candidates': 138, 'rules': 43, 'candidates_without_rule': 9}

## 2. The schedule
Week 1 = shelf price; each later week adds 5 points of shelf price. Week 10 (the last allowed week) is 45% off, so the 50% cap is only a safety net.

In [3]:
from shared.pricing_rules import discount_pct, scheduled_price
pd.DataFrame({"week_no": range(1, 11),
              "discount": [discount_pct(n) for n in range(1, 11)],
              "price_if_shelf_is_100": [scheduled_price(100, n) for n in range(1, 11)]})

   week_no  discount  price_if_shelf_is_100
0        1      0.00                  100.0
1        2      0.05                   95.0
2        3      0.10                   90.0
3        4      0.15                   85.0
4        5      0.20                   80.0
5        6      0.25                   75.0
6        7      0.30                   70.0
7        8      0.35                   65.0
8        9      0.40                   60.0
9       10      0.45                   55.0

## 3. Price the week (no sending yet)
Every candidate row comes back as PRICED or SKIPPED with a reason.

In [4]:
from jobs.pricing_engine.engine import price_week
from shared.warehouse import get_warehouse
rows = price_week(WEEK, get_warehouse())
recs = pd.DataFrame(rows)
print(recs.groupby(["status", "reason"], dropna=False).size().rename("rows"))
recs[recs.status == "PRICED"].head(10)

status   reason
PRICED   NaN                  126
SKIPPED  FLOOR_ABOVE_PRICE      3
         MISSING_RULE           6
         NOT_IN_PRODUCTS        3
Name: rows, dtype: int64

        week     sku pack_type  pack_qty region  week_no  shelf_price  current_price  discount_pct  recommended_price   binding  status reason         warning
9   2026-W39  100011    Single         1    NSW        6        33.99          27.19        0.2501              25.49  SCHEDULE  PRICED    NaN  ZERO_INVENTORY
10  2026-W39  100011    Single         1    QLD        6        33.99          27.19        0.2501              25.49  SCHEDULE  PRICED    NaN  ZERO_INVENTORY
11  2026-W39  100011    Single         1    VIC        6        33.99          27.19        0.2501              25.49  SCHEDULE  PRICED    NaN  ZERO_INVENTORY
12  2026-W39  100012    Single         1    NSW        5        20.99          17.84        0.2001              16.79  SCHEDULE  PRICED    NaN             NaN
13  2026-W39  100012    Single         1    QLD        5        20.99          17.84        0.2001              16.79  SCHEDULE  PRICED    NaN             NaN
14  2026-W39  100012    Single         1    VIC        5        20.99          17.84        0.2001              16.79  SCHEDULE  PRICED    NaN             NaN
15  2026-W39  100014    Single         1    NSW        1        17.99          17.99        0.0000              17.99  SCHEDULE  PRICED    NaN             NaN
16  2026-W39  100014    Single         1    QLD        1        17.99          17.99        0.0000              17.99  SCHEDULE  PRICED    NaN             NaN
17  2026-W39  100014    Single         1    VIC        1        17.99          17.99        0.0000              17.99  SCHEDULE  PRICED    NaN             NaN
18  2026-W39  100016    Single         1    NSW        6        26.99          21.59        0.2501              20.24  SCHEDULE  PRICED    NaN             NaN

## 4. Why each row got its price (`binding`)
SCHEDULE = the plain schedule; FLOOR / MAX_MARKDOWN / LADDER = a hard rule lifted the price; LAST_WEEK = capped at last week's price.

In [5]:
display(recs[recs.status == "PRICED"].groupby("binding").size().rename("rows"))
recs[(recs.status == "PRICED") & (recs.binding != "SCHEDULE")].head(8)

binding
LADDER        3
SCHEDULE    123
Name: rows, dtype: int64

         week     sku  pack_type  pack_qty region  week_no  shelf_price  current_price  discount_pct  recommended_price binding  status reason warning
120  2026-W39  100002  Multipack         6    NSW        4       221.94         199.75           0.1             199.74  LADDER  PRICED    NaN     NaN
121  2026-W39  100002  Multipack         6    QLD        4       221.94         199.75           0.1             199.74  LADDER  PRICED    NaN     NaN
122  2026-W39  100002  Multipack         6    VIC        4       221.94         199.75           0.1             199.74  LADDER  PRICED    NaN     NaN

## 5. Skipped rows and warnings
MISSING_RULE (no floor from SAP), FLOOR_ABOVE_PRICE (floor above last week's price), NOT_IN_PRODUCTS (article not in product master). ZERO_INVENTORY is a warning: the row is still priced.

In [6]:
display(recs[recs.status == "SKIPPED"].drop_duplicates(["sku", "pack_qty"])[["sku", "pack_type", "pack_qty", "week_no", "shelf_price", "current_price", "reason"]])
recs[recs.warning.notna()][["sku", "pack_qty", "region", "recommended_price", "warning"]]

        sku pack_type  pack_qty  week_no  shelf_price  current_price             reason
0    100000    Single         1        4        67.99          61.19       MISSING_RULE
3    100004    Single         1        6        60.99          48.79       MISSING_RULE
6    100009    Single         1        5        36.99          31.44  FLOOR_ABOVE_PRICE
117  999999    Single         1        1        24.99          19.99    NOT_IN_PRODUCTS

       sku  pack_qty region  recommended_price         warning
9   100011         1    NSW              25.49  ZERO_INVENTORY
10  100011         1    QLD              25.49  ZERO_INVENTORY
11  100011         1    VIC              25.49  ZERO_INVENTORY

## 6. One item's whole markdown path (region VIC): history + this week's recommendation

In [7]:
item = recs[(recs.status == "PRICED") & (recs.pack_qty == 1) & (recs.week_no >= 4) & (recs.region == "VIC")].iloc[0]
con = duckdb.connect(DB, read_only=True)
hist = con.sql(f"""SELECT week, week_no, shelf_price, price, round(1 - price / shelf_price, 3) AS discount
    FROM price_history WHERE sku = '{item.sku}' AND pack_qty = 1 AND region = 'VIC' AND is_clearance ORDER BY week""").df()
con.close()
new = pd.DataFrame([{"week": WEEK + " (recommended)", "week_no": item.week_no, "shelf_price": item.shelf_price,
                     "price": item.recommended_price, "discount": item.discount_pct}])
pd.concat([hist, new], ignore_index=True)

                     week  week_no  shelf_price  price  discount
0                2026-W34        1        33.99  33.99    0.0000
1                2026-W35        2        33.99  32.29    0.0500
2                2026-W36        3        33.99  30.59    0.1000
3                2026-W37        4        33.99  28.89    0.1500
4                2026-W38        5        33.99  27.19    0.2000
5  2026-W39 (recommended)        6        33.99  25.49    0.2501

## 7. Multipack ladder: per-item price of a pack vs its Single (same sku, region VIC)

In [8]:
pk = recs[(recs.status == "PRICED") & (recs.pack_qty > 1) & (recs.region == "VIC")].iloc[0]
both = recs[(recs.sku == pk.sku) & (recs.region == "VIC") & (recs.status == "PRICED")].copy()
both["unit_price"] = (both.recommended_price / both.pack_qty).round(2)
both[["sku", "pack_type", "pack_qty", "week_no", "recommended_price", "unit_price", "binding"]]

        sku  pack_type  pack_qty  week_no  recommended_price  unit_price binding
122  100002  Multipack         6        4             199.74       33.29  LADDER

## 8. Save to `price_recommendations` and check every hard rule with SQL
Each check must return 0 violations.

In [9]:
from jobs.pricing_engine.engine import save_recommendations
save_recommendations(DB, RUN, WEEK, rows)
con = duckdb.connect(DB, read_only=True)
def n(sql): return con.sql(sql).fetchone()[0]
P = "FROM price_recommendations p WHERE p.status = 'PRICED' AND p.run_id = '%s'" % RUN
print("saved rows                 :", n(f"SELECT count(*) FROM price_recommendations WHERE run_id = '{RUN}'"))
print("above last week's price    :", n(f"SELECT count(*) {P} AND p.recommended_price > p.current_price + 1e-9"))
print("below the SAP floor        :", n(f"""SELECT count(*) {P} AND p.recommended_price < (SELECT price_floor FROM business_rules r
                                        WHERE r.week = p.week AND r.sku = p.sku AND r.pack_qty = p.pack_qty) - 1e-9"""))
print("below 50% off shelf        :", n(f"SELECT count(*) {P} AND p.recommended_price < p.shelf_price * 0.5 - 0.01"))
print("beyond max_clearance_weeks :", n(f"""SELECT count(*) {P} AND p.week_no > (SELECT max_clearance_weeks FROM business_rules r
                                        WHERE r.week = p.week AND r.sku = p.sku AND r.pack_qty = p.pack_qty)"""))
print("multipack unit < Single    :", n(f"""SELECT count(*) {P} AND p.pack_qty > 1 AND EXISTS (SELECT 1 FROM price_recommendations s
        WHERE s.run_id = p.run_id AND s.sku = p.sku AND s.region = p.region AND s.pack_qty = 1 AND s.status = 'PRICED'
          AND p.recommended_price / p.pack_qty < s.recommended_price - 1e-9)"""))
con.close()

saved rows                 : 138
above last week's price    : 0
below the SAP floor        : 0
below 50% off shelf        : 0
beyond max_clearance_weeks : 0
multipack unit < Single    : 0

## 9. Send to SAP
The engine's `run()` prices, saves and POSTs the priced rows in batches, then stores SAP's per-record result on `price_recommendations`.

In [10]:
from jobs.pricing_engine.run import run
rows, results = run(WEEK, RUN, get_warehouse(), DB, client=write, batch_size=50)
print(Counter((r["status"], r["code"]) for r in results))
con = duckdb.connect(DB, read_only=True)
display(con.sql(f"SELECT status, reason, sap_status, sap_code, count(*) AS rows FROM price_recommendations WHERE run_id = '{RUN}' GROUP BY ALL ORDER BY 1, 2").df())
con.close()

Counter({('ACCEPTED', 'OK'): 126})

    status             reason sap_status sap_code  rows
0   PRICED                NaN   ACCEPTED       OK   126
1  SKIPPED  FLOOR_ABOVE_PRICE        NaN      NaN     3
2  SKIPPED       MISSING_RULE        NaN      NaN     6
3  SKIPPED    NOT_IN_PRODUCTS        NaN      NaN     3

## 10. Rerun the same run id: idempotent
SAP returns the stored results and holds no duplicates.

In [11]:
rows2, results2 = run(WEEK, RUN, get_warehouse(), DB, client=write)
print(Counter((r["status"], r["code"], r["duplicate"]) for r in results2))
print("SAP holds:", read.get("/pricing/conditions", params={"week": WEEK}).json()["count"], "conditions")

Counter({('ACCEPTED', 'OK', True): 126})
SAP holds: 126 conditions

## 11. What SAP holds vs what the engine recommended

In [12]:
held = pd.DataFrame(read.get("/pricing/conditions", params={"week": WEEK}).json()["items"])
sent = recs_sent = pd.DataFrame([r for r in rows2 if r["status"] == "PRICED"])
cmp = sent.merge(held, on=["sku", "pack_qty", "region"], how="left")
print("recommended:", len(sent), "| held by SAP:", len(held), "| missing in SAP:", int(cmp.price.isna().sum()),
      "| price differs:", int((cmp.price.notna() & ((cmp.price - cmp.recommended_price).abs() > 1e-9)).sum()))
held.head()

recommended: 126 | held by SAP: 126 | missing in SAP: 0 | price differs: 0

              run_id      week     sku  pack_qty region   price  valid_from    valid_to
0  2026-W39-notebook  2026-W39  100002         6    NSW  199.74  2026-09-21  2026-09-27
1  2026-W39-notebook  2026-W39  100002         6    QLD  199.74  2026-09-21  2026-09-27
2  2026-W39-notebook  2026-W39  100002         6    VIC  199.74  2026-09-21  2026-09-27
3  2026-W39-notebook  2026-W39  100004         6    NSW  365.94  2026-09-21  2026-09-27
4  2026-W39-notebook  2026-W39  100004         6    QLD  365.94  2026-09-21  2026-09-27

## 12. Reset SAP's received prices (to rerun sections 9-11)

In [13]:
from shared import db
from shared.sap_schema import schema
with db.connect() as c:
    c.execute(f"TRUNCATE {schema()}.price_conditions")
print("SAP holds", read.get("/pricing/conditions", params={"week": WEEK}).json()["count"], "conditions")

SAP holds 0 conditions